### ISSUE TITLE
2021.5.0 - Error: TemplateError('TypeError: 'NoneType' object is not subscriptable')

### ISSUE THREAD

**Issue by user897943** [lolouk44/CurrentCost_HA_CC#8]
The integration no longer loads/doesn't show any values. It's is now broken under 2021.5.0.

```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:72
Integration: Template (documentation, issues)
First occurred: May 6, 2021, 5:49:34 PM (2 occurrences)
Last logged: May 6, 2021, 5:49:34 PM

TemplateError('TypeError: 'NoneType' object is not subscriptable') while processing template 'Template("{{ state_attr("sensor.current_cost", "Temperature")[:-3] | float }}")' for attribute '_state' in entity 'sensor.currentcost_temperature'
TemplateError('TypeError: 'NoneType' object is not subscriptable') while processing template 'Template("{{ state_attr("sensor.current_cost", "Appliance 0")[:-2] | int }}")' for attribute '_state' in entity 'sensor.currentcost_power'
```

and:

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:391
First occurred: May 6, 2021, 5:49:34 PM (2 occurrences)
Last logged: May 6, 2021, 5:49:34 PM

Error while processing template: Template("{{ state_attr("sensor.current_cost", "Temperature")[:-3] | float }}")
Error while processing template: Template("{{ state_attr("sensor.current_cost", "Appliance 0")[:-2] | int }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 389, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1359, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 505, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 391, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not subscriptable
```

**Comment by user897943** [comment]
@lolouk44 Hi, sorry for tagging you, I know you must be super busy, I don't know how to fix this one, if you could please take a look it would be great, the sensor has been broken since the end of March 2021 :(

**Comment by lolouk44** [comment]
sorry I did not get notified of this.
do you get data in the sensor `sensor.current_cost`?
If no then the template won't work.
If yes, it would appear your template is incorrect.
can you set the custom component to debug and give me the logs please?
Add this to your configuration.yaml:
```yaml
logger:
  default: error
  logs:
    custom_components.currentcost: debug
```

**Comment by user897943** [comment]
It's fine, thanks for getting back to me on this one. This is the data reported by the sensor:
```
Temperature: null
Appliance 0: null
unit_of_measurement: W
friendly_name: Power Consumption
icon: mdi:flash-circle
device_class: power
```
Here's the output from the logger:

```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:72
Integration: Template (documentation, issues)
First occurred: 12:34:15 PM (2 occurrences)
Last logged: 12:34:15 PM

TemplateError('TypeError: 'NoneType' object is not subscriptable') while processing template 'Template("{{ state_attr("sensor.current_cost", "Temperature")[:-3] | float }}")' for attribute '_state' in entity 'sensor.currentcost_temperature'
TemplateError('TypeError: 'NoneType' object is not subscriptable') while processing template 'Template("{{ state_attr("sensor.current_cost", "Appliance 0")[:-2] | int }}")' for attribute '_state' in entity 'sensor.currentcost_power'
```
and:

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:391
First occurred: 12:34:15 PM (2 occurrences)
Last logged: 12:34:15 PM

Error while processing template: Template("{{ state_attr("sensor.current_cost", "Temperature")[:-3] | float }}")
Error while processing template: Template("{{ state_attr("sensor.current_cost", "Appliance 0")[:-2] | int }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 389, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1359, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 505, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 391, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not subscriptable
```

Just like on the first report. I am not getting anything from the sensor. It worked like a charm before the end of March update.
Thank you.

**Comment by lolouk44** [comment]
how did you install the custom-component? is it manually or via HACS?
If manually, you need to get the latest files from the repo. There was an update to HA in 2021.5 which required custom-components to have a version in the manifest file, which I added a couple of months ago.

**Comment by user897943** [comment]
I was actually the guy who fixed the manifest file and you did a pull request on that one, not sure if you'll remember now that I've mentioned :) I installed via HACS. It's the latest version that has the issue. Thanks.

**Comment by lolouk44** [comment]
lol I had forgotten you were to one who did the PR 🤣 
It sounds like you're not receiving any data from the Current Cost. If you're not receiving data the template sensors won't work. (it's actually a change I want to implement at some stage but it'll mean a breaking change so I've not done it yet)

Anyway back to your issue. My CC works so the HA update has nothing to do with it most likely. You're not getting any data from the CC so here are a few things you need to check:
- Is the CC is correctly connected? If you connected the CC to a different port you may need to adjust the port number/name in the HA config
- Does the CC display updates correctly?
- Check the batteries in the transmitter.
- You may need to pair the transmitter and the display again if you changed the batteries.
- What do you get when you type this in a terminal:
`ls /dev/serial/by-id/`
(You should see at a line like `usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0`)
- What else has changed around the time the CC stopped working? If just HA version have you tried to downgrade to see if it still works?

**Comment by user897943** [comment]
Haha no worries!!
The CC display is receiving data. I don't use batteries, I used a buck converted with a DC adaptor to permanently wire it up so it's always juiced up.
the command shows this:
usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0
Nothing changed. My config is still like this:

  - platform: currentcost
    serial_port: /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0
    name: Current Cost
    baudrate: 57600
    devices:
      - 0

**Comment by lolouk44** [comment]
Something feels odd, as though you do not receive data on the serial port (else you'd get something in the HA logs)
Stupid question, have you tried to reboot the computer? Clearly the CC is connected and recognised.
What else has changed in your setup since/around the time it stopped working?

**Comment by user897943** [comment]
The blue light on the serial adaptor is on, so it's definitely receiving power. It's also being recognized. I rebooted for sure. I tried to change the device from - 0 to - 1 and amending the template to Appliance 1, now rebooting... and it made no difference. I thought it wouldn't anyway because at least the Temperature reading should come through. I run HA on docker if it makes any difference!? I don't use docker compose so when I create my container I specify this key:
--device /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 which means it should be recognizing
I did docker exec -it homeassistant bash
I executed lsusb inside the HA container, and I see this:
Bus 001 Device 003: ID 067b:2303
Then I exited bash from within the container and ran lsusb in the raspi itself, I can see this:
Bus 001 Device 003: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
So clearly it is being detected and passed to the HA container... puzzling!

**Comment by lolouk44** [comment]
I honestly don't get it. Have ou unplugged the CC display from the power to have it restart in case it was stuck?

Each time the CC receives a info and sends it via serial, the custom component would display a line like this:
`2021-05-27 21:21:46 DEBUG (MainThread) [custom_components.currentcost.sensor] Line Received: <msg><src>CC128-v1.29</src><dsb>02951</dsb><time>00:44:01</time><tmpr>22.9</tmpr><sensor>2</sensor><id>00095</id><type>1</type><ch1><watts>00000</watts></ch1></msg>`
your logs should be inundated with these lines

**Comment by user897943** [comment]
Ok, I fixed it...
Here's what I've done.
My docker command is like this:
```
docker create --name homeassistant --net=host --restart always -it -v /etc/localtime:/etc/localtime:ro -v /home/myuser/blabla/home_assistant/:/config -v /home/myuser/blabla/nodered:/config/www/node_red -e variable="TZ=Europe/London" --device /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/currentcost --device /dev/ttyUSB-zwave:/dev/zwavestick --device /dev/ttyUSB-zigbee:/dev/zigbeestick --device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2197975-if00:/dev/conbee2 homeassistant/home-assistant:latest
```

Ignore everything except this part
```
--device /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/currentcost
```
Previously it was like this - notice there is no mount ":/dev/currentcost":
```
--device /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0
```
I added the mounts and then amended my configuration.yaml to pull from the devices as mounted on the container itself so in this case /dev contained device /dev/currentcost

I also removed privileged mode because frankly it's insecure, so I guess I killed two birds with one stone!

You might want to added this to documentation for Docker users, I could happily do later just not sure how so I'll have to look into it. Can the repo homepage be edited from a pull request?!?

Thank you very much for your help and attention, without you I wouldn't have pushed myself because I assumed the issue was the custom component... I am truly grateful for your valuable input.

**Comment by lolouk44** [comment]
Glad you fixed it :) not sure who's to blame here. Docker's [own doc](https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device
) lists  `--device=/dev/sdd` as a valid option so that should have worked for you too.
I'm actually now just wondering. Does reverting to the previous device command still fails? Probably yes but still wondering. Would not be the first time that I see a glitch make its way through and go away 😉 
I've updated the README just in case.
It might be an idea to raise an issue on HA's own github as it's now starting to sound like it's somehow related to the latest version

**Comment by user897943** [comment]
Thank you. Well, it was working until the update to 2021.5.0 then all of a sudden it stopped, if Docker changed something in their code/config with an update then it was a really weird coincidence, right?
Unfortunately I cannot raise issues on the HA github, I upset one of their really sensitive developers and they banned me... their loss, I used to report bugs but during a disagreement with the guy he opted to abuse his power. Shrug... Thanks for updating the documentation. I am tempted to try just for you lol. But you know the saying, if it's working don't fix it! haha.
